### ISSUE TITLE
termux:gui not installed?

### ISSUE THREAD

**Issue by olav2021** [tareksander/termux-gui-python-bindings#1] opened 2021-12-01 15:30 UTC
Hello,
I try to run the hello world example with termux 117 and termux-gui 0.1.4 and pythonbinding 0.1.3, armv8l Android.

94@localhost ~
╰─➤  python helloworld.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/termuxgui/connection.py", line 36, in __init__
    main = mainss.accept()[0]
  File "/data/data/com.termux/files/usr/lib/python3.10/socket.py", line 293, in accept
    fd, addr = self._accept()
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/hello.py", line 5, in <module>
    with tg.Connection() as c:
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/termuxgui/connection.py", line 62, in __init__
    raise RuntimeError("Could not connect to Termux:GUI. Is the plugin installed?")
RuntimeError: Could not connect to Termux:GUI. Is the plugin installed?

-------------------------
You mentioned something about building termux from source, right? Do I really have to?

**Comment by tareksander** [comment] 2021-12-01 16:12
I'm still waiting for f-droid to review the plugin so it will be included on f-droid, but I now provide an apk to use it, because the process is taking longer than I expected. The downside is that the apk is only compatible with the Github build of Termux, because I don't have the f-droid signing key to sign it.  
To install it you first have to uninstall Termux and all plugins from f-droid (be sure to backup your files if you want to keep them), and then reinstall Termux from Github:  
https://github.com/termux/termux-app/actions/runs/1485416404  
And the plugins you want:  
https://github.com/termux/termux-api/actions/runs/1486934030  
https://github.com/termux/termux-tasker/actions/runs/1225499291  
https://github.com/termux/termux-styling/actions/runs/992419269  
https://github.com/termux/termux-widget/releases/tag/v0.13.0  
  
Then you can install Termux:GUI: https://github.com/tareksander/termux-gui/releases/tag/0.1.3

**Comment by poggenpower** [comment] 2022-03-18 18:18
I this still in review on the f-droid side?

**Comment by tareksander** [comment] 2022-03-18 19:11
No, but the installation won't work due to signing key issues: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10240  
The only option is using the Github apk for Termux and Termux:GUI.

**Comment by Vosjedev** [comment] 2022-11-23 11:25
is there any chance of this apearing on fdroid in the future?

**Comment by tareksander** [comment] 2022-11-23 11:37
[The f-droid team disabled the app because it needs to be re-signed](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12035). I don't know when that will happen. The alternative is that my [PR for plugins without shared UID](https://github.com/termux/termux-app/pull/2921) gets merged and a new Termux version is released, because it won't need to be re-signed then. I don't know what will happen sooner. In any case distribution on f-droid would be possible then. For any new information you can watch the [pinned issue about this on the Termux:GUI repo](https://github.com/termux/termux-gui/issues/4). Closing this now as it's a duplicate of that issue.

**Closed by tareksander** 2022-11-23 11:37 UTC
